AllCops:
  Exclude:
    - /**/tmp/**/*
    - /**/bin/**/*
    - /**/script/**/*
    - /**/vendor/**/*
    - /**/db/migrate/**/*
    - /**/db/schema.rb
    - /**/lib/tasks/**/*
    - /**/config/**/*
    - /**/Gemfile
    - /**/*.gemspec
    - /**/Guardfile
    - /**/Rakefile
    - /**/simple_form.rb
    - /**/simple_form_bootstrap.rb
    - /**/spec/rails_helper.rb
    - /**/spec/spec_helper.rb

  DisplayCopNames: true





Bundler/OrderedGems:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false





Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/FirstArrayElementLineBreak:
  Enabled: true  # Disabled by default

Layout/FirstHashElementLineBreak:
  Enabled: true  # Disabled by default

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Allow create(:foo, bar: 1+1)
Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/UselessAssignment:
  Exclude:
    - /**/spec/**/*





Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 100
  IgnoredPatterns:
    - ^class
    - ^module
    - has_many
    - has_one
    - belongs_to
    - has_and_belongs_to_many
    - ^Given
    - ^When
    - ^Then

  # TODO : Remove
  Exclude:
    - /**/app/pdfs/**/*

Metrics/MethodLength:
  Max: 30
  Exclude:
    - /**/app/pdfs/**/*

Metrics/ModuleLength:
  Enabled: false

Naming/PredicateName:
  Enabled: false





Performance/Casecmp:
  Enabled: false





Rails:
  Enabled: true  # Disabled by default

Rails/OutputSafety:
  Enabled: false

Rails/SaveBang:
  Enabled: true  # Disabled by default

Rails/SkipsModelValidations:
  Exclude:
    - /**/spec/**/*
    - /**/features/**/*





Security/Eval:
  Enabled: false





Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/ClassAndModuleChildren:
  Enabled: false
  # EnforcedStyle: compact

Style/CommentedKeyword:
  Enabled: false

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  IncludeTernaryExpressions: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/GuardClause:
  MinBodyLength: 3

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Style/IfInsideElse:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: true  # Disabled by default

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/MultilineBlockChain:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: "()"
    "%i": "()"
    "%I": "()"
    "%r": "{}"
    "%w": "()"
    "%W": "()"

Style/RedundantReturn:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
